# Generated by Django 4.2.5 on 2023-09-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webSocket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logininfo',
            name='role',
            field=models.IntegerField(default=0),
        ),
    ]
